# Retraining the Model

To detect a concept drift, ideally we should compare two distributions: the one used to train the model and the one of the new data. If they are different, we can assume that a concept drift has occurred and we should retrain the model.
In practice, we use a metric that is a proxy for the distribution of the data, such as the model's performance on a validation set. If the performance drops significantly, it may indicate that the model is no longer accurate and needs to be retrained.

## Why Retraining is Important

- To ensure the model remains accurate and relevant over time as new data becomes available.
- Incorporating new data can help the model adapt to changes in the rental market, such as shifts in demand, pricing trends, and other factors that may affect rental prices (concept drift)

## How to Retrain the Model


### Steps:
- Input: a drift report generated by the drift detection module
- Output: a new model trained using all data
    - the previous test set becomes part of the training set


### Metrics to Monitor for Concept Drift
- Mean Absolute Error (MAE)
  - I used as trigger the ration of the current MAE over the previous MAE. If the ratio is greater than 1.5, we consider that a concept drift has occurred and we retrain the model.
- Additionally, as visual check I used Evidently to monitor the marginal distro of the features and the target variable. 