# Modelling the Rental Market

Regarding the modelling of the rental market, we are trying to predict the average rent for meter squared in the next semester based on the previous semester's data. Now the approaches can be different, but we are using a simple approach that is to use the previous semester's average rent for meter squared as a feature to predict the next semester's average rent for meter squared. In the future if performance is not good enough more feature engineering can be done to improve the model or even models that can capture the temporal nature of the data can be used.

## Features
Two types of features are used in the model:

- Numeric features:
    - loc_mid_lag (previous semester's average rent for meter squared)
- Categorical features:
    - zona_omi (area of the city)
    - tipologia (property type)
    - stato (property status)

## Target Variable
The target variable is:

    - loc_mid (next semester's average rent for meter squared)

-----

## Data splitting
    - Training set: all semesters except the last one
    - Test set: last semester

## Versioning
    - after each training, a dictionary with metrics is computed
    - two directories are created: baseling with time in the name and latest with the latest model and metrics
        - inside each the model and the metrics are saved
        - additionally, also the dataset is versioned and saved in the same directory using SHA256
    - ML flow is used to track the experiments and metrics

## Modelling Approach
- the current pipeline is:
    - Missing value are set to 0
    - OrdinalEncoder transforms categorical features into numeric values (set to -1 not seen categories)
    - HistGradientBoostingRegressor is used as the model


### Model Selection
- Currently we are using HistGradientBoostingRegressor, but we can try other models in the future.

----
### Metrics
- MAE - Mean Absolute Error 
    - No sensitive to outliers
- RMSE - Root Mean Squared Error
- R2 - Coefficient of Determination
    - Measures how well the model explains the variance in the target variable
    - 1.0 means perfect prediction, 
    - 0 means the model is no better than a horizontal line (mean of the target variable)
    - negative values indicate that the model is worse than a horizontal line.
