name: Render and deploy Quarto site

# garantisce che GITHUB_TOKEN possa scrivere i contenuti (push su gh-pages)
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (Quarto)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https ca-certificates
          wget -O quarto.deb https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo apt install -y ./quarto.deb
          quarto --version

      - name: Render Quarto site
        run: |
          quarto render

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
